#!/usr/bin/env bash
#installing nginx1

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

str="\nfrontend http_web\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend custom_backend\n"
str2="backend custom_backend\n\tbalance roundrobin\n\tserver web01 3.92.27.64:80 check\n\tserver web02 54.242.225.135:80 check\n"
sudo echo -e $str | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo -e $str2 | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start