#!/usr/bin/env bash
# trap process
sudo touch /var/run/holbertonscript.pid
$BASHPID > /var/run/holbertonscript.pid
trap 'echo I hate the kill command; rm /var/run/holbertonscript.pid' SIGTERM exit
trap 'echo Y U no love me?!' SIGINT exit
trap 'rm /var/run/holbertonscript.pid' SIGQUIT exit
while true
do
    echo "To infinity and beyond"
    sleep 2
done