#!/usr/bin/env bash
# prints file contents 
file="/etc/passwd"
x=1
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
    printf '%s:%s:%s\n' "$f1" "$f3" "$f6"
    if ((x == 0)); then
        printf '%s:%s:%s\n' "$f2" "$f4" "$f5" "$f7"
    fi
done <"$file"